version: '3'

services:
  server:
    build: .
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 80:80
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: englitopia
    volumes:
      - ./db:/var/lib/mysql