version: '3'

services:
  server:
    image: serhiicho/englitopia:server
    container_name: server
    environment: 
      - APACHE_RUN_USER=#1000
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 7000:80
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: serhiicho/englitopia:db
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: englitopia